POST http://localhost:3000/reports
Content-Type: application/json

{
    "make":"toyota",
    "model":"corolla",
    "year":1980, 
    "milage": 10000,
    "lng":0,
    "lat":0,
    "price":50000
} 

### Approve an existing report  
PATCH  http://localhost:3000/reports/10
Content-Type: application/json 

{
  "approved": true
} 

### 
GET http://localhost:3000/reports?make=toyoto&model=corolla&lng=0&lat=0&milage=20000&year=1980
Content-Type: application/json

